import { ThemeConfiguration } from './config/theme.config'
import { NotificationProvider } from './context/notification.context'
import './globals.css'


export const metadata = {
  title: 'Bienestar Universidad Nacional',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <NotificationProvider>
        <ThemeConfiguration>
          <body>{children}</body>
        </ThemeConfiguration>
      </NotificationProvider>
    </html>
  )
}
