import { ThemeConfiguration } from './config/theme.config'
import './globals.css'


export const metadata = {
  title: 'Bienestar Universidad Nacional',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <ThemeConfiguration>
        <body>{children}</body>
      </ThemeConfiguration>
    </html>
  )
}
